### ISSUE TITLE
jiff is not defined

### ISSUE THREAD

**Issue by AndrewIsh** [cujojs/jiff#25]
I suspect this is more of an issue regarding my lack of understanding of Browserify, so apologies if that's the case!

I put jiff through Browserify:
```
browserify /bower_components/jiff/jiff.js > /bower_components/jiff/jiff_bundle.js
```
I added a script tag for jiff_bundle.js. Now when I call jiff.diff, I get the following:
```
ReferenceError: jiff is not defined
```

Any idea what I'm doing wrong? Thanks :)

**Comment by AndrewIsh** [comment]
Sorry, it was as I suspected, I needed to specify the following in browserify:
```
browserify bower_components/jiff/jiff.js --standalone jiff > bower_components/jiff/jiff_bundle.js
```

**Comment by briancavalier** [comment]
Hey @AndrewIsh, no problem at all.  Glad you found the `--standalone` option.
